version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_CONVEX_URL=${VITE_CONVEX_URL_PROD}
    image: indianrobinhood-frontend
    container_name: indianrobinhood-frontend
    restart: unless-stopped
    ports:
      - "8002:8080"
      
  ingestor:
    build:
      context: .
      dockerfile: Dockerfile.ingestor
    image: indianrobinhood-ingestor
    container_name: indianrobinhood-ingestor
    restart: unless-stopped
    # This env_file directive is now the ONLY source for environment variables
    env_file:
      - .env
    volumes:
      - ingestor_cache:/app/cache

volumes:
  ingestor_cache:
    driver: local
