version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_CONVEX_URL=${VITE_CONVEX_URL_PROD}
    image: indianrobinhood-frontend
    container_name: indianrobinhood-frontend
    restart: unless-stopped
    ports:
      - "8002:8080"
    volumes:
      - token_config:/app/config
      
  ingestor:
    build:
      context: .
      dockerfile: Dockerfile.ingestor
    image: indianrobinhood-ingestor
    container_name: indianrobinhood-ingestor
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ingestor_cache:/app/cache
      - token_config:/app/config

volumes:
  ingestor_cache:
    driver: local
  token_config:
    driver: local
