version: '3.8'

services:
  # In production, the frontend is a self-contained Nginx server.
  frontend:
    build:
      context: .
      dockerfile: Dockerfile # This now builds the final nginx image
    image: indianrobinhood-frontend
    container_name: indianrobinhood-frontend
    restart: unless-stopped
    ports:
      # Expose the container's port 80 on the host's port 8002 to avoid conflicts
      - "8002:80"

  # The Python data ingestor service for production.
  ingestor:
    build:
      context: .
      dockerfile: Dockerfile.ingestor
    image: indianrobinhood-ingestor
    container_name: indianrobinhood-ingestor
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Mount a named volume to persist the securities master cache
      - ingestor_cache:/app/cache
    # IMPORTANT: In production, this must point to your deployed Convex URL.
    # You should add VITE_CONVEX_URL_PROD to your .env file after deploying.
    environment:
      - CONVEX_URL=${VITE_CONVEX_URL_PROD}

# Define the named volume for persistent cache storage
volumes:
  ingestor_cache:
    driver: local
